<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Admin_sasaran_mutu_model extends CI_Model
{

    // public $table = 'tbl_samutdep';
    // public $id = 'id_samutdept';
    // public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_user_level,nama_level');
        $this->datatables->from('tbl_user_level');
		//add this line for join
        $this->datatables->where('id_user_level != 1');
		$this->datatables->where('id_user_level != 2');
        $this->datatables->edit_column('nama_level_v', '<a href="Admin_sasaran_mutu/view_tahunnya/$1">$2</a>', 'id_user_level, nama_level');

        //$this->datatables->join('table2', 'tbl_samutdep.field = table2.field');
        return $this->datatables->generate();
    }

    function json_2($id) {
        $this->datatables->select('tbl_tahun_qhse.tahun,tbl_samutdep.tahun_samut');
        $this->datatables->from('tbl_samutdep');
        //add this line for join
        $this->datatables->join('tbl_tahun_qhse', 'tbl_samutdep.tahun_samut = tbl_tahun_qhse.id_thn','LEFT');
        $this->datatables->join('tbl_user', 'tbl_samutdep.department = tbl_user.id_users','LEFT');
        $this->datatables->join('tbl_user_level', 'tbl_user.id_users = tbl_user_level.id_user_level','LEFT');
        //add this line for where
        if($id == 0){

        }else{
            $this->datatables->where('tbl_user.id_user_level',$id);

        }        
        $this->datatables->group_by('tbl_samutdep.tahun_samut');
        // $this->datatables->edit_column('nama_tahun_v', '<a href="SasaranMutu_department/view_samutdep/$1">$2</a>', 'tahun_samut, tahun');
        $this->datatables->edit_column('nama_tahun_v', '<a href="Admin_sasaran_mutu/view_samutdep/$1">$2</a>', 'tahun_samut, tahun');

        //$this->datatables->join('table2', 'tbl_samutdep.field = table2.field');
        return $this->datatables->generate();
    }

    function json_3() {
        $this->datatables->select('id_samutdept,pihak_kepentingan,kbthn_hrpn,peluang_ancaman,main_proses,sub_proses,sub_sub_proses,input,proses_pdca,quality_assurance,quality_control,output,penerima_output,samut,kpi,pic,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,rata_rata,created_date,created_by,modify_date,modify_by');
        $this->datatables->from('tbl_samutdep');
        
		$this->datatables->where('tahun_samut', $this->input->post('id_thn'));
		$this->datatables->where('department', $this->input->post('id_users'));

        //add this line for join
        //$this->datatables->join('table2', 'tbl_samutdep.field = table2.field');
        return $this->datatables->generate();
	}
    

}

/* End of file All_samut_model.php */
/* Location: ./application/models/All_samut_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-28 03:07:16 */
/* http://harviacode.com */