<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class All_samut_model extends CI_Model
{

    public $table = 'tbl_samutdep';
    public $id = 'id_samutdept';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_samutdept,pihak_kepentingan,kbthn_hrpn,peluang_ancaman,main_proses,sub_proses,sub_sub_proses,input,proses_pdca,quality_assurance,quality_control,output,penerima_output,samut,kpi,pic,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,rata_rata,department,tahun_samut,tahun');
        $this->datatables->from('tbl_samutdep');
		//add this line for join
        $this->datatables->join('tbl_tahun_qhse', 'tbl_samutdep.tahun_samut = tbl_tahun_qhse.id_thn', 'left');		
        //$this->datatables->join('table2', 'tbl_samutdep.field = table2.field');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_samutdept', $q);
	$this->db->or_like('pihak_kepentingan', $q);
	$this->db->or_like('kbthn_hrpn', $q);
	$this->db->or_like('peluang_ancaman', $q);
	$this->db->or_like('main_proses', $q);
	$this->db->or_like('sub_proses', $q);
	$this->db->or_like('sub_sub_proses', $q);
	$this->db->or_like('input', $q);
	$this->db->or_like('proses_pdca', $q);
	$this->db->or_like('quality_assurance', $q);
	$this->db->or_like('quality_control', $q);
	$this->db->or_like('output', $q);
	$this->db->or_like('penerima_output', $q);
	$this->db->or_like('samut', $q);
	$this->db->or_like('kpi', $q);
	$this->db->or_like('pic', $q);
	$this->db->or_like('jan', $q);
	$this->db->or_like('feb', $q);
	$this->db->or_like('mar', $q);
	$this->db->or_like('apr', $q);
	$this->db->or_like('may', $q);
	$this->db->or_like('jun', $q);
	$this->db->or_like('jul', $q);
	$this->db->or_like('aug', $q);
	$this->db->or_like('sep', $q);
	$this->db->or_like('oct', $q);
	$this->db->or_like('nov', $q);
	$this->db->or_like('dec', $q);
	$this->db->or_like('rata_rata', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('modify_date', $q);
	$this->db->or_like('modify_by', $q);
	$this->db->or_like('department', $q);
	$this->db->or_like('tahun_samut', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_samutdept', $q);
	$this->db->or_like('pihak_kepentingan', $q);
	$this->db->or_like('kbthn_hrpn', $q);
	$this->db->or_like('peluang_ancaman', $q);
	$this->db->or_like('main_proses', $q);
	$this->db->or_like('sub_proses', $q);
	$this->db->or_like('sub_sub_proses', $q);
	$this->db->or_like('input', $q);
	$this->db->or_like('proses_pdca', $q);
	$this->db->or_like('quality_assurance', $q);
	$this->db->or_like('quality_control', $q);
	$this->db->or_like('output', $q);
	$this->db->or_like('penerima_output', $q);
	$this->db->or_like('samut', $q);
	$this->db->or_like('kpi', $q);
	$this->db->or_like('pic', $q);
	$this->db->or_like('jan', $q);
	$this->db->or_like('feb', $q);
	$this->db->or_like('mar', $q);
	$this->db->or_like('apr', $q);
	$this->db->or_like('may', $q);
	$this->db->or_like('jun', $q);
	$this->db->or_like('jul', $q);
	$this->db->or_like('aug', $q);
	$this->db->or_like('sep', $q);
	$this->db->or_like('oct', $q);
	$this->db->or_like('nov', $q);
	$this->db->or_like('dec', $q);
	$this->db->or_like('rata_rata', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('modify_date', $q);
	$this->db->or_like('modify_by', $q);
	$this->db->or_like('department', $q);
	$this->db->or_like('tahun_samut', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file All_samut_model.php */
/* Location: ./application/models/All_samut_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-28 03:07:16 */
/* http://harviacode.com */