<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Evaluasi_model extends CI_Model
{

    public $table = 'tbl_evaluasi';
    public $id = 'id_evaluasi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_evaluasi,id_tahun_eva,tahun_eva,evaluasi,analisa,id_samut_eva,sasaran_mutu_eva,target_eva,deadline_eva,pic_eva,keterangan_eva');
        $this->datatables->from('tbl_evaluasi');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_evaluasi.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('evaluasi/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('evaluasi/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('evaluasi/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_evaluasi');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_evaluasi', $q);
	$this->db->or_like('id_tahun_eva', $q);
	$this->db->or_like('tahun_eva', $q);
	$this->db->or_like('evaluasi', $q);
	$this->db->or_like('analisa', $q);
	$this->db->or_like('id_samut_eva', $q);
	$this->db->or_like('sasaran_mutu_eva', $q);
	$this->db->or_like('target_eva', $q);
	$this->db->or_like('deadline_eva', $q);
	$this->db->or_like('pic_eva', $q);
	$this->db->or_like('keterangan_eva', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_evaluasi', $q);
	$this->db->or_like('id_tahun_eva', $q);
	$this->db->or_like('tahun_eva', $q);
	$this->db->or_like('evaluasi', $q);
	$this->db->or_like('analisa', $q);
	$this->db->or_like('id_samut_eva', $q);
	$this->db->or_like('sasaran_mutu_eva', $q);
	$this->db->or_like('target_eva', $q);
	$this->db->or_like('deadline_eva', $q);
	$this->db->or_like('pic_eva', $q);
	$this->db->or_like('keterangan_eva', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }


    function fetch_samut($id_tahun)
    {
     $this->db->where('tahun_samut', $id_tahun);
     $this->db->where('department', $this->session->userdata('id_users',TRUE));
     $this->db->order_by('id_samutdept', 'ASC');
     $query = $this->db->get('tbl_samutdep');
     $output = '<option value="">Select Sasaran Mutu</option>';
     foreach($query->result() as $row)
     {
      $output .= '<option value="'.$row->id_samutdept.'">'.$row->samut.'</option>';
     }
     return $output;
    }
}

/* End of file Evaluasi_model.php */
/* Location: ./application/models/Evaluasi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-02-28 07:28:37 */
/* http://harviacode.com */